import fs from "node:fs";
import path from "node:path";

import { discoverRenderComponents } from "../src/lib/discover-render-components";

const OUT_DIR = "src/generated";
const OUT_FILE = path.join(OUT_DIR, "server-registry.ts");

const files = await discoverRenderComponents();

function buildImportLine(file: (typeof files)[number]): string {
  const names = [
    ...(file.defaultExport ? [file.defaultExport.localName] : []),
    ...file.namedExports.map((e) => e.localName),
  ];

  if (file.defaultExport && file.namedExports.length === 0) {
    return `import ${file.defaultExport.localName} from ${JSON.stringify(file.importPath)};`;
  }

  if (!file.defaultExport && file.namedExports.length > 0) {
    return `import { ${names.join(", ")} } from ${JSON.stringify(file.importPath)};`;
  }

  const defaultName = file.defaultExport!.localName;
  const named = file.namedExports.map((e) => e.localName).join(", ");
  return `import ${defaultName}, { ${named} } from ${JSON.stringify(file.importPath)};`;
}

const imports = files.map(buildImportLine).join("\n");

const registryLines = files.flatMap((file) => {
  const bindings = [
    ...(file.defaultExport ? [file.defaultExport] : []),
    ...file.namedExports,
  ];
  return bindings.map(
    (b) =>
      `  ${JSON.stringify(b.registryKey)}: asComponent(${b.localName}),`,
  );
});

const content = `// Auto-generated by scripts/generate-server-registry.ts — do not edit manually.
import type { ComponentType } from "react";

${imports}

type AnyComponent = ComponentType<Record<string, unknown>>;

function asComponent(component: unknown): AnyComponent {
  return component as AnyComponent;
}

export const serverComponents: Record<string, AnyComponent> = {
${registryLines.join("\n")}
};

export function buildServerRegistry(): Map<string, AnyComponent> {
  return new Map(Object.entries(serverComponents));
}
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, content, "utf8");

const count = files.reduce(
  (n, f) => n + (f.defaultExport ? 1 : 0) + f.namedExports.length,
  0,
);

console.log(
  `[generate-server-registry] Wrote ${count} components from ${files.length} files to ${OUT_FILE}`,
);
