import fs from "node:fs";
import path from "node:path";

import { discoverClientComponents } from "../src/lib/discover-client-components";

const OUT_DIR = "src/generated";
const OUT_FILE = path.join(OUT_DIR, "client-registry.ts");
const OUT_SERVER_FILE = path.join(OUT_DIR, "client-server-registry.ts");

const entries = await discoverClientComponents();

if (entries.length === 0) {
  console.warn("[generate-client-registry] No client components discovered.");
}

const lazyEntries = entries
  .map((e) => {
    const lazyPath = `../components/${e.lazyImportPath.replace(/^\.\//, "")}`;
    return `  ${JSON.stringify(e.rctKey)}: lazy(() => import(${JSON.stringify(lazyPath)})),`;
  })
  .join("\n");

const registryExports = entries
  .map((e) => `  ${JSON.stringify(e.rctKey)},`)
  .join("\n");

const serverImports = entries
  .map((e, idx) => {
    const importPath = `../components/${e.lazyImportPath.replace(/^\.\//, "")}`;
    return `import ${e.componentName} from ${JSON.stringify(importPath)};`;
  })
  .join("\n");

const serverEntries = entries
  .map((e) => `  ${JSON.stringify(e.rctKey)}: ${e.componentName},`)
  .join("\n");

const content = `// Auto-generated by scripts/generate-client-registry.ts — do not edit manually.
import { lazy } from "react";

export const clientRegistryKeys = [
${registryExports}
] as const;

export type ClientRegistryKey = (typeof clientRegistryKeys)[number];

export const clientComponents: Record<
  string,
  React.LazyExoticComponent<React.ComponentType<any>>
> = {
${lazyEntries}
};
`;

const serverContent = `// Auto-generated by scripts/generate-client-registry.ts — do not edit manually.
import type { ComponentType } from "react";

${serverImports}

type AnyComponent = ComponentType<any>;

export const clientServerComponents: Record<string, AnyComponent> = {
${serverEntries}
};
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT_FILE, content, "utf8");
fs.writeFileSync(OUT_SERVER_FILE, serverContent, "utf8");

console.log(
  `[generate-client-registry] Wrote ${entries.length} entries to ${OUT_FILE}`,
);
console.log(
  `[generate-client-registry] Wrote ${entries.length} entries to ${OUT_SERVER_FILE}`,
);
